/* Local real app + temporary SQLite. Telegram SDK is a test double. No native-device claim. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium,webkit}=require('playwright');
const root=process.env.MINI_APP_QA_ROOT||process.cwd();
const {fixtureServer,installSdk}=require(path.join(root,'scripts/mini_app_redesign_browser_qa.cjs'));
const engine=process.env.DESIGN_QA_ENGINE||'chromium', phase=process.env.DESIGN_QA_PHASE||'AFTER';
const out=process.env.DESIGN_QA_OUT||path.join(process.env.TEMP,'twitchsignal-design-audit-2026-10-03',phase,'polish-'+engine);
fs.mkdirSync(out,{recursive:true});
const report={engine,phase,native:'NOT TESTED',checks:[],screenshots:[],errors:[],external:[]};
const sourceSnapshot=()=>Object.fromEntries(fs.readdirSync(path.join(root,'bot/mini_app_ui')).filter(n=>/\.(js|css|html)$/.test(n)).map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'bot/mini_app_ui',n))).digest('hex')]));
report.sources=sourceSnapshot();
const check=(name,value,detail)=>report.checks.push({name,pass:!!value,detail});
let browser,scenarioIndex=0;
async function picture(page,name){const file=name+'.png';await page.screenshot({path:path.join(out,file),animations:'disabled'});report.screenshots.push(file);}
async function run(scenario,fn){scenarioIndex++;if(process.env.DESIGN_QA_CASES&&!process.env.DESIGN_QA_CASES.split(',').includes(String(scenarioIndex)))return;if(process.env.DESIGN_QA_SCOPE==='geometry'&&scenarioIndex>1)return;const server=await fixtureServer(scenario);const context=await browser.newContext({viewport:{width:390,height:844},locale:'ru-RU'});try{const page=await context.newPage(),origin=new URL(server.url).origin;page.on('pageerror',e=>report.errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='telegram.org')return r.fulfill({body:'',contentType:'application/javascript'});if(u.origin===origin)return r.continue();report.external.push(u.origin+u.pathname);return r.abort();});await installSdk(page);await fn(page,server.url);}finally{await context.close();await server.close();}}
const start=async(page,url)=>{await page.goto(url);await page.locator('#content[data-viewer-state="ready"]').waitFor();};
const button=(p,n)=>p.getByRole('button',{name:n,exact:true});
async function insets(page,top=59,content=47,bottom=34){await page.evaluate(({top,content,bottom})=>{Object.assign(Telegram.WebApp,{isFullscreen:!!top,safeAreaInset:{top,bottom,left:0,right:0},contentSafeAreaInset:{top:content,bottom:0,left:0,right:0},viewportHeight:innerHeight,viewportStableHeight:innerHeight});for(const name of ['safeAreaChanged','contentSafeAreaChanged','viewportChanged','fullscreenChanged'])for(const fn of window.__qaSdk.events.get(name)||[])fn();},{top,content,bottom});}
async function metrics(page){return page.evaluate(()=>{const r=n=>{const v=n.getBoundingClientRect();return {x:v.x,y:v.y,right:v.right,bottom:v.bottom,width:v.width,height:v.height}};return {header:r(document.querySelector('.app-header')),nav:r(document.querySelector('#tab-bar')),overflow:document.documentElement.scrollWidth>innerWidth+1,fields:[...document.querySelectorAll('input[type=time]')].map(n=>({input:r(n),label:r(n.parentElement)}))};});}
(async()=>{browser=await(engine==='webkit'?webkit:chromium).launch({headless:false});
await run('free-six',async(p,url)=>{
await start(p,url);await insets(p);
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});await insets(p);const m=await metrics(p);check('safe-top-'+width,m.header.y>=106+8,m.header);check('overflow-'+width,!m.overflow);check('floating-navigation-'+width,m.nav.x>=8&&m.nav.bottom<=844-34-8,m.nav);await picture(p,'home-'+width);}
const active=await p.locator('#tab-bar [aria-current]').evaluate(n=>({bg:getComputedStyle(n).backgroundColor,other:getComputedStyle(n.parentElement).backgroundColor}));check('selected-tab-shape',active.bg!=='rgba(0, 0, 0, 0)'&&active.bg!==active.other,active);
check('stream-title-is-marked',await p.locator('.stream-title').first().textContent().then(s=>s.startsWith('«')&&s.endsWith('»')));
await button(p,'Профиль').click();await p.locator('#content[data-profile-state=ready]').waitFor();await picture(p,'profile');await button(p,'Тема приложения').click();await picture(p,'theme-dialog');const bounds=await p.getByRole('dialog').boundingBox();check('dialog-safe-bounds',bounds.y>=114&&bounds.y+bounds.height<=802,bounds);await button(p,'Тёмная').click();await button(p,'Закрыть').click();await button(p,'Уведомления').click();await p.locator('input[type=time]').first().waitFor();
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});const m=await metrics(p);check('time-field-bounds-'+width,m.fields.every(f=>f.input.x>=f.label.x-1&&f.input.right<=f.label.right+1),m.fields);await picture(p,'quiet-dark-'+width);}
await p.setViewportSize({width:390,height:460});await insets(p);await p.locator('input[type=time]').last().focus();await picture(p,'quiet-short-viewport');check('short-viewport-no-overflow',!(await metrics(p)).overflow);
await p.setViewportSize({width:900,height:900});await insets(p,0,0,0);await button(p,'Главная').click();await picture(p,'desktop');check('desktop-no-mobile-gap',(await metrics(p)).header.y<=32);
});
await run('free-empty',async(p,url)=>{await start(p,url);await picture(p,'new-viewer-home');const add=button(p,'Добавить стримера');check('first-step-direct-add',await add.count()===1);if(await add.count()){check('first-step-primary',!(await add.getAttribute('class')).includes('secondary'));await add.click();}else{await button(p,'Мои стримеры').click();await button(p,'Добавить стримера').click();}await p.getByRole('dialog').waitFor();await picture(p,'add-dialog');const field=p.getByRole('dialog').locator('input').first();await field.fill('alpha');await button(p,'Добавить Alpha').waitFor();await picture(p,'add-result');await button(p,'Добавить Alpha').click();await p.getByRole('dialog').waitFor({state:'hidden'});await picture(p,'added-success');await button(p,'Стримеры').click();await p.locator('[data-open-streamer]').first().click();await picture(p,'streamer-detail');const remove=button(p,'Удалить подписку');let confirmation='';p.once('dialog',async d=>{confirmation=d.message();await d.dismiss();});await remove.click();check('delete-confirmation-and-cancel',confirmation.includes('Alpha')&&await remove.count()===1,confirmation);await picture(p,'delete-cancelled');});
await run('payment-off',async(p,url)=>{await start(p,url);await button(p,'Тариф').click();await button(p,'Оформить Зритель Plus — 150 ₽').waitFor();await picture(p,'viewer-plus');await button(p,'Оформить Зритель Plus — 150 ₽').click();await button(p,'Telegram Stars').waitFor();const note=p.locator('[data-payment-availability]');check('availability-before-method',await note.count()===1);if(await note.count()){const a=await note.boundingBox(),b=await p.locator('.purchase-methods').boundingBox();check('availability-above-method',a.y<b.y);}await picture(p,'payment-before-selection');await button(p,'Telegram Stars').click();await p.getByText('Оплата временно недоступна. Мы заканчиваем подключение платёжной системы.',{exact:true}).waitFor();await picture(p,'payment-unavailable');check('permanent-unavailable-no-retry',await button(p,'Повторить').count()===0);
await button(p,'Стример').click();await button(p,'Тариф').click();await button(p,'Оформить Стример Plus — 300 ₽').waitFor();await picture(p,'streamer-plus');});
await run('free-empty',async(p,url)=>{let release;const hold=new Promise(r=>release=r);await p.route('**/app/api/bootstrap',async r=>{await hold;await r.fulfill({status:503,contentType:'application/json',body:'{}'});});await p.goto(url,{waitUntil:'domcontentloaded'});await picture(p,'bootstrap-loading');release();await p.getByRole('heading',{name:'Не удалось загрузить приложение',exact:true}).waitFor();await picture(p,'bootstrap-offline');check('bootstrap-offline-has-retry',await button(p,'Повторить вход').count()===1);if(await button(p,'Повторить вход').count()){await p.unroute('**/app/api/bootstrap');await button(p,'Повторить вход').click();await p.getByRole('heading',{name:'Главная',exact:true}).waitFor();check('bootstrap-retry-recovers',true);}});
await run('channel-permissions',async(p,url)=>{await start(p,url);await button(p,'Стример').click();await p.locator('#content .navigation-row').first().waitFor();await p.locator('#content .navigation-row').first().click();await button(p,'Включить публикации').waitFor();await button(p,'Включить публикации').click();await button(p,'Приостановить публикации').waitFor();await picture(p,'publishing-success');await p.evaluate(async()=>fetch('/_qa/channel-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({permission:'bot_member'})}));await button(p,'Проверить права').click();await p.locator('[data-permission-status=bot_member]').waitFor();check('permission-refresh-no-stale-success',await p.getByText('Публикации включены. Бот отправит обычный пост при следующем подтверждённом эфире.',{exact:true}).count()===0);await picture(p,'changed-permission');});
await run('free-six',async(p,url)=>{await start(p,url);await insets(p);await p.evaluate(()=>{Telegram.WebApp.safeAreaInset.top=70;Telegram.WebApp.contentSafeAreaInset.top=50;for(const fn of window.__qaSdk.events.get('fullscreenChanged')||[])fn();});check('fullscreen-event-updates-geometry',(await metrics(p)).header.y>=128);await p.evaluate(()=>{Telegram.WebApp.safeAreaInset.top=0;Telegram.WebApp.contentSafeAreaInset.top=0;for(const fn of window.__qaSdk.events.get('fullscreenFailed')||[])fn();});check('fullscreen-failed-restores-geometry',(await metrics(p)).header.y<=32);});
for(const deniedStatus of [401,403])await run('free-empty',async(p,url)=>{await p.route('**/app/api/bootstrap',r=>r.fulfill({status:deniedStatus,contentType:'application/json',body:JSON.stringify({error:'invalid_init_data'})}));await p.goto(url);await p.getByText('Время входа истекло. Откройте приложение заново из чата бота.',{exact:true}).waitFor();check('auth-failure-no-inplace-retry',await button(p,'Повторить вход').count()===0);check('auth-failure-no-private-data',await p.locator('.streamer-row').count()===0);await picture(p,'expired-auth-'+deniedStatus);});

await run('free-empty',async(p,url)=>{let release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);let privateCalls=0;p.on('request',r=>{if(r.url().includes('/app/api/')&&!r.url().endsWith('/bootstrap'))privateCalls++;});await p.route('**/app/api/bootstrap',async r=>{const response=await r.fetch();arrived();await held;await r.fulfill({response});});await p.goto(url,{waitUntil:'domcontentloaded'});await seen;const before=await p.locator('#content').textContent();await p.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));release();await p.waitForTimeout(300);check('pagehide-no-late-bootstrap-ui',await p.locator('#content').textContent()===before);check('pagehide-no-private-requests',privateCalls===0,privateCalls);});
await run('channel-permissions',async(p,url)=>{await start(p,url);await button(p,'Стример').click();await p.locator('#content .navigation-row').first().waitFor();await p.locator('#content .navigation-row').first().click();await button(p,'Включить публикации').waitFor();let release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);await p.route('**/app/api/streamer/communities/toggle',async r=>{const response=await r.fetch();arrived();await held;await r.fulfill({response});});await button(p,'Включить публикации').click();await seen;await button(p,'Мой канал').click();const response=p.waitForResponse('**/app/api/streamer/profile');release();await response;await p.locator('#content .navigation-row').first().filter({hasText:'Публикации включены'}).waitFor();check('late-publishing-feedback-stays-in-context',await p.getByText('Публикации включены. Бот отправит обычный пост при следующем подтверждённом эфире.',{exact:true}).count()===0);await picture(p,'late-publishing-new-context');});

await run('free-empty',async(p,url)=>{let calls=0,release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);await p.route('**/app/api/bootstrap',async r=>{calls++;if(calls===1)return r.fulfill({status:503,contentType:'application/json',body:'{}'});arrived();await held;await r.continue();});await p.goto(url);await button(p,'Повторить вход').waitFor();await button(p,'Повторить вход').evaluate(b=>{b.click();b.click();});await seen;check('retry-single-flight',calls===2,calls);await button(p,'Стример').click();await p.locator('#app-menu').click();await p.getByRole('dialog').getByRole('button',{name:'Поддержка',exact:true}).focus();release();await p.getByRole('heading',{name:'Мой канал',exact:true}).waitFor();check('retry-keeps-selected-route',await p.locator('#mode-switch [aria-pressed=true]').textContent()==='Стример');check('background-render-keeps-dialog-focus',await p.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)));await p.keyboard.press('Tab');check('dialog-traps-tab',await p.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)));await p.evaluate(()=>window.__qaSdk.back());check('back-closes-only-dialog',await p.getByRole('dialog').count()===0&&await p.getByRole('heading',{name:'Мой канал',exact:true}).count()===1);});
await run('free-empty',async(p,url)=>{let calls=0;await p.route('**/app/api/bootstrap',r=>r.fulfill({status:++calls===1?503:403,contentType:'application/json',body:'{}'}));await p.goto(url);await button(p,'Повторить вход').waitFor();await button(p,'Повторить вход').click();await p.getByText('Время входа истекло. Откройте приложение заново из чата бота.',{exact:true}).waitFor();check('retry-then-auth-denial-stops',calls===2&&await button(p,'Повторить вход').count()===0);});

await run('channel-permissions',async(p,url)=>{await start(p,url);await button(p,'Стример').click();await button(p,'Подключить Telegram-канал').waitFor();await p.evaluate(()=>Telegram.WebApp.requestChat=(id,cb)=>cb(true));await button(p,'Подключить Telegram-канал').click();await p.getByText('Выбор отправлен. Проверяем канал…',{exact:true}).waitFor();let release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);await p.route('**/app/api/streamer/community-intent/cancel',async r=>{const response=await r.fetch();arrived();await held;await r.fulfill({response});});await button(p,'Отменить выбор').click();await seen;await p.locator('#content .navigation-row').first().click();await p.getByRole('heading',{name:'Telegram-канал',exact:true}).waitFor();const done=p.waitForResponse('**/app/api/streamer/community-intent/cancel');release();await done;await p.waitForTimeout(100);check('late-channel-cancel-stays-in-context',await p.getByText('Добавление нового канала отменено.',{exact:true}).count()===0);await picture(p,'late-cancel-new-context');});
await run('channel-permissions',async(p,url)=>{await start(p,url);await button(p,'Стример').click();await p.locator('#content .navigation-row').first().waitFor();await p.locator('#content .navigation-row').first().click();await button(p,'Включить публикации').waitFor();await button(p,'Включить публикации').click();await button(p,'Приостановить публикации').waitFor();let release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);await p.route('**/app/api/streamer/profile',async r=>{arrived();await held;await r.continue();});await button(p,'Проверить права').click();await seen;check('permission-refresh-clears-success-immediately',await p.getByText('Публикации включены. Бот отправит обычный пост при следующем подтверждённом эфире.',{exact:true}).count()===0);release();});

await run('legal-unready',async(p,url)=>{await start(p,url);await button(p,'Профиль').click();await button(p,'Поддержка').waitFor();await button(p,'Поддержка').click();await button(p,'Пользовательское соглашение').waitFor();await button(p,'Пользовательское соглашение').click();await button(p,'Обновить документ').waitFor();await p.setViewportSize({width:390,height:650});await p.evaluate(()=>document.documentElement.style.fontSize='32px');await button(p,'Обновить документ').focus();await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const focus=await button(p,'Обновить документ').boundingBox(),nav=await p.locator('#tab-bar').boundingBox();check('keyboard-focus-above-floating-navigation',focus.y>=0&&focus.y+focus.height<=nav.y-4,{focus,nav});await picture(p,'legal-text200-keyboard-focus');});
check('javascript-errors',!report.errors.length,report.errors);check('external-requests',!report.external.length,report.external);
check('source-snapshot-unchanged',JSON.stringify(report.sources)===JSON.stringify(sourceSnapshot()));
report.status=report.checks.every(c=>c.pass)?'PASS':'FAIL';
})().catch(e=>{report.status='ERROR';report.failure=e.stack;}).finally(async()=>{await browser?.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,failed:report.checks.filter(c=>!c.pass).map(c=>c.name),failure:report.failure,screenshots:report.screenshots.length}));process.exitCode=report.status==='PASS'?0:1;});



